//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMediMan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mediManEntities : DbContext
    {
        public mediManEntities()
            : base("name=mediManEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVIDADES> ACTIVIDADES { get; set; }
        public virtual DbSet<CONSULTAS> CONSULTAS { get; set; }
        public virtual DbSet<DEPORTES> DEPORTES { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<FICHAS> FICHAS { get; set; }
        public virtual DbSet<PACIENTES> PACIENTES { get; set; }

        public System.Data.Entity.DbSet<SistemaMediMan.Models.ViewModels.ListPacienteViewModel> ListPacienteViewModels { get; set; }

        public System.Data.Entity.DbSet<SistemaMediMan.Models.ViewModels.ListActividadViewModel> ListActividadViewModels { get; set; }
    }
}
