//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMediMan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class FICHAS
    {
        public int ID { get; set; }
        public int PAC_ID { get; set; }
        [Required]
        [DisplayName("Médico Tratante")]
        public string MEDICO { get; set; }
        [Required]
        [DisplayName("Tratamiento")]
        public string TRATAMIENTO { get; set; }
        [Required]
        [DisplayName("Medicamento")]
        public string MEDICAMENTO { get; set; }
        [Required]
        [DisplayName("Diagnóstico")]
        public string DIAGNOSTICO { get; set; }
        [Required]
        [DisplayName("Antecedentes Mórbidos")]
        public string ANTMORBIDO { get; set; }
    
        public virtual PACIENTES PACIENTES { get; set; }
    }
}
