//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMediMan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Clase Paciente. Contiene todos los atributos que corresponden a la clase paciente
    /// También se incluyen sus llaves foráneas.
    /// </summary>
    public partial class PACIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTES()
        {
            this.CONSULTAS = new HashSet<CONSULTAS>();
            this.FICHAS = new HashSet<FICHAS>();
        }
    
        public int ID { get; set; }
        [Required]
        [DisplayName("Deporte")]
        public int DEP_ID { get; set; }
        [Required]
        [DisplayName("Actividad")]
        public int ACT_ID { get; set; }
        [Required]
        [DisplayName("RUT")]
        public string RUT { get; set; }
        [Required]
        [DisplayName("Nombre")]
        [RegularExpression("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+",ErrorMessage ="Este campo solo admite letras")]
        public string NOMBRE { get; set; }
        [Required]
        [DisplayName("Apellido")]
        [RegularExpression("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+", ErrorMessage = "Este campo solo admite letras")]
        public string APELLIDOP { get; set; }
        
        [DisplayName("Apellido")]
        [RegularExpression("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+", ErrorMessage = "Este campo solo admite letras")]
        public string APELLIDOM { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime FDENAC { get; set; }
        [Required]
        [DisplayName("Edad")]
        public int EDAD { get; set; }
        [Required]
        [DisplayName("Sexo")]
        public bool SEXO { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Télefono")]
        [RegularExpression(@"^\(?([9]{1})\)?[-. ]?([0-9]{4})?([0-9]{4})$", ErrorMessage = "Formato inválido")]
        public string TELEFONOP { get; set; }
        [Required]
        [DisplayName("Previsión")]
        public string PREVISION { get; set; }
        [Required]
        [DisplayName("Dirección")]
        [RegularExpression("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+", ErrorMessage = "Este campo solo admite letras")]
        public string CALLE { get; set; }
        [Required]
        [DisplayName("Número")]
        public int NUMCALLE { get; set; }
        
        [DisplayName("Dpto")]
        public string DPTO { get; set; }
        [Required]
        [DisplayName("Comuna")]
        [RegularExpression("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+", ErrorMessage = "Este campo solo admite letras")]
        public string COMUNA { get; set; }
        
    
        public virtual ACTIVIDADES ACTIVIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTAS> CONSULTAS { get; set; }
        public virtual DEPORTES DEPORTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHAS> FICHAS { get; set; }
    }
}
